# Preliminary Analysis in Mothur {#prelim-analysis}

> First initiate `mothur` then run the following commands on `mothur cli` to generate downstream input data.

## Setting input and output directories
```bash
set.dir(input=data/, output=data/mothurdata/)
```

## Getting count table
```bash
count.groups(shared=final.tx.shared)
```

## Subsample dataset for group comparison {#subsampling}
```bash
sub.sample(shared=final.tx.shared)
```

## Summary table with richness and diversity metrics
Using different calculators to compute:

- Number of sequences
- Coverage
- Observed species
- Inverse Simpson
- Chao1 estimations
- Shannon

> We can specify more calculators if needed.

### Using unfitered data
```bash
summary.single(shared=final.tx.shared, 
  calc=nseqs-coverage-sobs-invsimpson-chao-npshannon)
```

### Using a subsample
```bash
summary.single(shared = final.tx.1.subsample.shared, 
  calc=nseqs-coverage-sobs-invsimpson-chao-npshannon)
```

## Rarefaction dataset at 100%
```bash
rarefaction.single(shared=final.tx.shared, 
  calc=sobs, freq=100)
```

## Rarefaction dataset at 25%
```bash
rarefaction.single(shared=final.tx.shared, 
  calc=sobs, freq=25)
```

## Distance matrix
Generating a phylip-formatted distance matrix for describing the dissimilarity (1-similarity) among the groups:

- The `jclass` calculator returns Jaccard index.
- The `jest` calculator returns estimate of Jaccard index and is computed using `Chao1` richness estimates.
- The `thetayc` calculator returns the Yue & Clayton measure of dissimilarity.
- The `braycurtis` calculator returns the Bray-Curtis measure of dissimilarity

```bash
dist.shared(shared = final.tx.1.subsample.shared, 
  calc=jclass-jest-thetayc-braycurtis)
```

## Newick-formatted tree
- Uses phylip-formatted distance matrix.
```bash
tree.shared(phylip=final.tx.1.subsample.braycurtis.1.lt.dist)
```
## PCoa and NMDS axes data
- Uses phylip-formatted distance matrix

```bash
pcoa(phylip=final.tx.1.subsample.braycurtis.1.lt.dist)
nmds(phylip=final.tx.1.subsample.braycurtis.1.lt.dist, mindim=3, maxdim=3)
```


