theme: jekyll-theme-cayman
show_downloads: true
title: Microbioma Data Analysis in R PART 1
github:
  is_project_page: true
description: A practical user guide for bioinformatics analysis of microbiome data.
